[[language]]
name = "nix"
scope = "source.nix"
injection-regex = "nix"
file-types = ["nix"]
shebangs = []
roots = []
comment-token = "#"
language-server = { command = "nil" }
indent = { tab-width = 2, unit = "  " }
formatter = { command = "nixpkgs-fmt" }
auto-format = true
